### ISSUE TITLE
Rider 2023.2 incompatibility

### ISSUE THREAD

**Issue by ForNeVeR** [chylex/Rider-VCS-Group-By-Project#2]
IntelliJ 2023.2 has renamed certain things in its workspace model API, and the plugin started to throw exceptions in 2023.2 EAP builds of Rider:
```
java.lang.NoClassDefFoundError: com/intellij/workspaceModel/ide/WorkspaceModel
	at com.chylex.intellij.rider.vcsgroupbyproject.ProjectChangesGroupingPolicy$Companion.getSingleProjectEntity(ProjectChangesGroupingPolicy.kt:73)
	at com.chylex.intellij.rider.vcsgroupbyproject.ProjectChangesGroupingPolicy$Companion.access$getSingleProjectEntity(ProjectChangesGroupingPolicy.kt:66)
	at com.chylex.intellij.rider.vcsgroupbyproject.ProjectChangesGroupingPolicy.getParentNodeFor(ProjectChangesGroupingPolicy.kt:37)
	at com.intellij.openapi.vcs.changes.ui.TreeModelBuilder.lambda$insertChangeNode$3(TreeModelBuilder.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:923)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:76)
	at com.intellij.openapi.vcs.changes.ui.TreeModelBuilder.insertChangeNode(TreeModelBuilder.java:428)
	at com.intellij.openapi.vcs.changes.ui.TreeModelBuilder.insertChangeNode(TreeModelBuilder.java:413)
	at com.intellij.openapi.vcs.changes.ui.TreeModelBuilder.setChangeLists(TreeModelBuilder.java:223)
	at com.intellij.openapi.vcs.changes.ChangesViewManager$ChangesViewToolWindowPanel.refreshView(ChangesViewManager.java:772)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.vcs.changes.ui.BackgroundRefresher.requestRefresh$lambda$5$lambda$4(BackgroundRefresher.kt:79)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

To make it work in 2023.2, a fix would be required (mostly the entities were moved to a new project, I think `Alt+Enter` should fix the issues).

For example, a similar fix in AvaloniaRider looks [like this](https://github.com/ForNeVeR/AvaloniaRider/commit/274668cd914c9c32f68fd33419130b8b2049cbf8):
```diff
- import com.intellij.workspaceModel.ide.WorkspaceModel
+ import com.intellij.platform.backend.workspace.WorkspaceModel
```

Please consider upgrading the plugin for newer builds of the IDE. Thanks!

Also, feel free to ask if you need help with that.

**Comment by chylex** [comment]
Will fix in a few weeks, the Rider SDK is too large for me to download atm.
